baseURL = "/"
languageCode = "en-us"
title = "pgillet$ >_"
theme = "noteworthy"

[params]
# Main
email = "mailto:pascalgillet@ymail.com"
#facebook = "#"
twitter = "https://twitter.com/psclgllt"
#instagram = "#"
#tumblr = "#"
#reddit = "#"
#pinterest = "#"
#youtube = "#"
#vimeo = "#"
#weibo = "#"
#vk = "#"
linkedin = "https://www.linkedin.com/in/pascal-gillet-a3171b13/"

# Writing
medium = "https://medium.com/@psclgllt"
#blogger = "#"
#wordpress = "#"

# Creative & Visual
#dribbble = "#"
#behance = "#"
#deviantart = "#"
flickr = "https://www.flickr.com/photos/96202293@N04/"

# Audio & Music
#soundcloud = "#"

# Programming
github = "https://github.com/pgillet"
#stackoverflow = "#"
#gitlab = "#"
#codepen = "#"

# Academic
googlescholar = "https://scholar.google.com/citations?user=Xx6tZQkAAAAJ&hl=fr"
#impactstory = "#"
#orcid = "#"

# Menu links along the sidebar navigation.
[[menu.main]]
	identifier = "about"
	name = "About"
	url = "/about/webcontent/index.html"
	weight = 1 # Weight is an integer used to sort the menu items. The sorting goes from smallest to largest numbers. If weight is not defined for each menu entry, Hugo will sort the entries alphabetically.

[[menu.main]]
	identifier = "tags"
	name = "Tags"
	url = "/tags/"
	weight = 2

[[menu.main]]
	name = "Archives"
	identifier = "archives"
	url = "/archives/"
	weight = 3
